### PR TITLE
Element name

### PR DESCRIPTION
**Pull request by ChasingNeutrons**
Figured the hail of sequential pull requests may take a while so we can get this one rolling anyway!

### CODE REVIEW

**Review by simondrichards — APPROVED** [review]
All looks good to me. 

I wonder if 'Aluminium' will get accepted as the example in the user's guide 😉

**Comment by simondrichards** [comment]
Merging and ready for pull request to openmc-dev.

**Comment by simondrichards** [comment]
Thanks @ChasingNeutrons,

I merged your pull request but I notice that the Travis CI builds are failing on your fork. Do you know the reason for this?

**Comment by ChasingNeutrons** [comment]
Hi Simon,

I've been scratching my head on this one... The failure is in 'test_mgxs_library_distribcell', and it does seem to be unique to me, when comparing with Mikolaj's test struggles. However, I also can't easily identify where my messing with the code has affected things - I don't think add_element is involved in the calculation at all! It seems as if Travis passes when using Python 3.5, but not with more recent version. If I'm lucky, it may just be that this test was a bit broken to begin with and I'm simply not up to date with the main OpenMC branch - I'll sort that out and then hopefully Travis should be happy.

**Comment by simondrichards** [comment]
Yeah, I noticed your branch is a bit behind. As you say, maybe this was broken already when you forked and it has now been fixed. Hopefully updating your branch will sort it. Good luck.

**Comment by ChasingNeutrons** [comment]
Seems to have solved it. Will get on the pull request now.

**Pull request merged**
